#!/bin/sh
#

refname="$1"
old_revision="$2"
new_revision="$3"

# enforced custom commit message format
function check_message_format {
  revisions=$(git rev-list $old_revision..$new_revision)
  IFS='\n' read -ra array <<< "$revisions"
  for rid in "${!array[@]}"; do 
	revision=${array[rid]}
    message=$(git cat-file commit $revision | sed '1,/^$/d')
	grepped=$(echo $message | grep -i "case [0-9]\+")
    if [ -z "$grepped" ] ; then
		echo "Your message is not formatted correctly" >&2
		echo "The message was: $message" >&2
		exit 1
    fi
  done
}

check_message_format

exit 0
